FROM alpine:latest

LABEL author="Konrad Baechler <konrad@diva.exchange>" \
  maintainer="Konrad Baechler <konrad@diva.exchange>" \
  name="diva" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://diva.exchange"

COPY entrypoint-build.sh /

# 1. install deps, clone and build.
# 2. strip binaries.
# 3. Purge all dependencies and other unrelated packages, including build directory.
RUN mkdir -p "/home/i2pd" \
  && apk --no-cache add \
    cmake \
    make \
    gcc \
    g++ \
    libtool \
    zlib-dev \
    boost-dev \
    build-base \
    openssl-dev \
    openssl \
    git \
    autoconf \
    automake \
  && chmod +x /entrypoint-build.sh

# Create the volume to keep the built I2P binary
VOLUME [ "/home/i2pd/" ]
WORKDIR "/home/i2pd/"
ENTRYPOINT ["/entrypoint-build.sh"]
