FROM debian:stable-slim

LABEL author="Konrad Baechler <konrad@diva.exchange>" \
  maintainer="Konrad Baechler <konrad@diva.exchange>" \
  name="diva" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://diva.exchange"

# Expose git branch, tag and URL variables as arguments
ARG GIT_BRANCH="openssl"
ARG REPO_URL="https://github.com/PurpleI2P/i2pd.git"

# 1. install deps, clone and build.
# 2. strip binaries.
# 3. Purge all dependencies and other unrelated packages, including build directory.
RUN mkdir -p "/home/i2pd" \
  && apt-get update \
  && apt-get -y install \
    cmake \
    make \
    gcc \
    g++ \
    build-essential \
    libboost-date-time-dev \
    libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-system-dev \
    libssl-dev \
    zlib1g-dev \
    openssl \
    git \
  && mkdir -p /tmp/gitclone \
  && cd /tmp/gitclone \
  && git clone -b ${GIT_BRANCH} ${REPO_URL} \
  && cd i2pd/build \
  && cmake . \
  && make \
  && mv i2pd /home/i2pd/i2pd-x86_64-debian \
  && strip /home/i2pd/i2pd-x86_64-debian \
  && chmod u+x /home/i2pd/i2pd-x86_64-debian \
  && cd /tmp/gitclone/i2pd/contrib \
  && cp -r certificates /home/i2pd/certificates \
  && cd /tmp/gitclone/i2pd/ \
  && cp LICENSE /home/i2pd/ \
  && cp ChangeLog /home/i2pd/

# Create the volume to keep the built I2P binary
VOLUME [ "/home/i2pd/" ]
WORKDIR "/home/i2pd/"
CMD [ "/bin/sh" ]
