FROM alpine:3.16

LABEL author="DIVA.EXCHANGE Association <contact@diva.exchange>" \
  maintainer="DIVA.EXCHANGE Association <contact@diva.exchange>" \
  name="diva-i2p" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://diva.exchange"

COPY conf/ /i2pd/conf/
COPY network/ /i2pd/network/
COPY certificates/ /i2pd/data/certificates/
COPY entrypoint.sh /
COPY bin/i2pd /i2pd/bin/i2pd

# install deps && build i2p binary
RUN mkdir -p /i2pd/data/addressbook \
  && mkdir /i2pd/tunnels.null \
  && mkdir /i2pd/tunnels.source.conf.d \
  && mkdir /i2pd/tunnels.conf.d \
  # i2p runtime dependencies
  && apk --no-cache add \
    boost-filesystem \
    boost-system \
    boost-program_options \
    boost-date_time \
    openssl \
    musl-utils \
    libstdc++ \
    sed \
    miniupnpc \
  && cp /i2pd/conf/addresses-initial.org.csv /i2pd/data/addressbook/addresses.csv \
  && addgroup -g 1000 i2pd \
  && adduser -u 1000 -G i2pd -s /bin/sh -h "/i2pd" -D i2pd \
  && chown -R i2pd:i2pd /i2pd \
  && chmod 0700 /i2pd/bin/i2pd \
  && chmod +x /entrypoint.sh

VOLUME [ "/i2pd/data/" ]
WORKDIR "/i2pd/"
ENTRYPOINT ["/entrypoint.sh"]
