FROM alpine:latest

LABEL author="Konrad Baechler <konrad@getdiva.org>" \
  maintainer="Konrad Baechler <konrad@getdiva.org>" \
  name="diva" \
  description="Distributed digital value exchange upholding security, reliability and privacy" \
  url="https://getdiva.org"

# Expose git branch, tag and URL variables as arguments
ARG GIT_BRANCH="openssl"
ARG REPO_URL="https://github.com/PurpleI2P/i2pd.git"

# 1. install deps, clone and build.
# 2. strip binaries.
# 3. Purge all dependencies and other unrelated packages, including build directory.
RUN mkdir -p "/home/i2pd" \
  && apk --no-cache --virtual .build-deps add \
    cmake \
    make \
    gcc \
    g++ \
    libtool \
    zlib-dev \
    boost-dev \
    build-base \
    openssl-dev \
    openssl \
    git \
    autoconf \
    automake \
  && mkdir -p /tmp/gitclone \
  && cd /tmp/gitclone \
  && git clone -b ${GIT_BRANCH} ${REPO_URL} \
  && cd i2pd/build \
  && cmake -DWITH_AESNI=ON . \
  && make \
  && mv i2pd /home/i2pd/i2pd-x86_64-aesni \
  && strip /home/i2pd/i2pd-x86_64-aesni \
  && chmod u+x /home/i2pd/i2pd-x86_64-aesni \
  && cd /tmp \
  && rm -fr /tmp/gitclone \
  && apk --purge del \
    .build-deps

# Create the volume to keep the built I2P binary
VOLUME [ "/home/i2pd/" ]
WORKDIR "/home/i2pd/"
CMD [ "/bin/sh" ]